### ISSUE TITLE
{"success":false,"error":"failed to process request before timeout","duration":0}

### ISSUE THREAD

**Issue by ne0ark** [neilenns/node-deepstackai-trigger#450]
**Describe the bug**
The request's failing for some reason.

**Log entries**
{"success":false,"error":"failed to process request before timeout","duration":0}

**Installation details**
 - OS: Ubuntu
 - Docker setup Portainer

**Additional context**
Using deep stack version: https://hub.docker.com/layers/deepquestai/deepstack/gpu/images/sha256-1a02e4e784c90eb109dd1aaa8cdf340dfb334875dfc140974a7dece68741326a?context=explore

**Comment by neilenns** [comment]
I'm not familiar with Portainer so I'm not going to be able to help much with this. Common things to look at are whether the networking setup in Portainer allows communication between this project and Deepstack. If the two Docker containers can't talk to each other you might get that error.

**Comment by ne0ark** [comment]
This issue seems to be an issue with Deepstack latest version.

**Comment by neilenns** [comment]
Does it work if you roll back to an older Deepstack Docker image?

**Comment by ne0ark** [comment]
> Does it work if you roll back to an older Deepstack Docker image?

Haven't tried yes will try it out. Here is the issue: https://forum.deepstack.cc/t/gpu-2022-01-1-no-objects-detected/1343

**Comment by neilenns** [comment]
Well... that looks like a Deepstack bug then so there's not much I can do about it. Try rolling back to the previous image.

**Comment by ne0ark** [comment]
@neilenns Did Deepstack anything? Current version in GPU docker brach and NVDIA 510 drivers. I am getting no detection:

----
2022-01-23T10:07:55-05:00 [Trigger Garage] /MotionEye/Garage/images/Garage-2022-01-23-10-07-48.jpg: Analyzing
2022-01-23T10:07:55-05:00 [Trigger Garage] /MotionEye/Garage/images/Garage-2022-01-23-10-07-48.jpg: No objects detected. (171 ms)
---

Not sure if something needs to up be updated in deepstack-trigger.

**Comment by neilenns** [comment]
I don't follow their development work, I suggest either:

1. Rolling back to an older version of their GPU image
2. Trying a non-GPU image
